// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybggbbekoxgkeyvkiech.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZ2diYmVrb3hna2V5dmtpZWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjUwOTcsImV4cCI6MjA2NTU0MTA5N30.1dKUTNLQ02eTSKEbkVhpDUs-0woXhYimjlPYQPIiplo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);